//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity_northwind_project.service
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SIPARISDETAY_LIST
    {
        public int SIPARIS_DETAY_ID { get; set; }
        public int URUN_ID { get; set; }
        public string URUN_AD { get; set; }
        public decimal FIYAT { get; set; }
        public int ADET { get; set; }
        public int ID { get; set; }
        public int PERSONEL_ID { get; set; }
        public int MUSTERI_ID { get; set; }
    }
}
